### ISSUE TITLE
Not working with jQuery 3.11.2

### ISSUE THREAD

**Issue by lukere-us** [akumagamo/jquery-plugin-tempgauge#4]
The plugin does not support new jQuery versions.
Not working with jQuery 3.11.2

**Comment by akumagamo** [comment]
Thank for this information, I will fix this.

**Comment by akumagamo** [comment]
> The plugin does not support new jQuery versions.
> Not working with jQuery 3.11.2

@lakshmanpalitha  I cant find the mentioned Version (3.11.2). And with the latest Version 3.5.1 (on the jquery homepage) standard and slim, it works.
Do you have a link to that Version (you mentioned) , to a jquery CDN or Repo or ...? 
If not I will close this Issue.

Thanks in advance
